# from: http://willmendesneto.github.io/2015/02/16/using-travis-ci-for-run-angularjs-unit-tests/

language: node_js
node_js:
  - '0.12'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma grunt-cli jshint'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages

after_script:
  - 'grunt' # or other command for build, run tests, etc
